// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj2DfAsij3Lceldzfo7BWVAweWrK_NRec',
    appId: '1:280054758838:web:290d2c1e0b4ca1e0ca5517',
    messagingSenderId: '280054758838',
    projectId: 'campushub-2d76b',
    authDomain: 'campushub-2d76b.firebaseapp.com',
    storageBucket: 'campushub-2d76b.firebasestorage.app',
    measurementId: 'G-TZ8Y9SJTF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0NYChJUFyixcJK3X36c51IvmnTm2pJVE',
    appId: '1:280054758838:android:dea9925426722aabca5517',
    messagingSenderId: '280054758838',
    projectId: 'campushub-2d76b',
    storageBucket: 'campushub-2d76b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFdp3LO6lhspqIEKECnGIJbPT2bOmRdCo',
    appId: '1:280054758838:ios:d687022d3e6801cdca5517',
    messagingSenderId: '280054758838',
    projectId: 'campushub-2d76b',
    storageBucket: 'campushub-2d76b.firebasestorage.app',
    iosBundleId: 'com.example.campusHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFdp3LO6lhspqIEKECnGIJbPT2bOmRdCo',
    appId: '1:280054758838:ios:d687022d3e6801cdca5517',
    messagingSenderId: '280054758838',
    projectId: 'campushub-2d76b',
    storageBucket: 'campushub-2d76b.firebasestorage.app',
    iosBundleId: 'com.example.campusHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj2DfAsij3Lceldzfo7BWVAweWrK_NRec',
    appId: '1:280054758838:web:dd7aa47bc26de2e4ca5517',
    messagingSenderId: '280054758838',
    projectId: 'campushub-2d76b',
    authDomain: 'campushub-2d76b.firebaseapp.com',
    storageBucket: 'campushub-2d76b.firebasestorage.app',
    measurementId: 'G-RK6S4FQXRW',
  );

}